tables:
  - name: base
    fields:
    - name: code
      type: text
      isPrimary: true
    - name: created_by
      type: text
    - name: updated_by
      type: text
    - name: updated_at
      type: timestamp
    - name: created_at
      type: timestamp

types:
  text:
    rustType: String
  integer:
    rustType: i128
  date:
    rustType: chrono::NaiveDate
  timestamp:
    rustType: chrono::NaiveDateTime